name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [8.0.403]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore tools
        run: dotnet tool restore
      - name: Check formatting
        run: dotnet fantomas --check run.fs src templates
      - name: Run build
        run: dotnet run build
      - name: Test templates
        run: dotnet run test-templates
